### ISSUE TITLE
Constructed Wetlands - colour scales

### ISSUE THREAD

**Issue by mz8i** [npalomin/shi_dataset_cdmx#2]
For the CW colour scale, the documentation mentions jenks breaks - and the colour values in the Readme are given only for the break number (1, 2, 3 etc).

- Do we want to hardcode the pre-calculated thresholds, or should we calculate them dynamically each time?
- How does the colour scale translate between the different values (%, sqm, total budget) - do we need to calculate the breaks individually for each variable?
- We want some colour scale that enables easy comparisons, for example when the user changes the budget value with a slider. Would this mean we need to calculate the breaks on the maximum extent of the values for each variable, rather than dynamically for what's shown on the screen right now?

**Comment by npalomin** [comment]
A new commit specifies class intervals for COLONIAS (sqm) and ALCALDIAS (pesos).
- we want to hardcode the pre-calculated thresholds
- class intervals (values) are specified for COLONIAS and ALCALDIAS
- we need to test the behaviour of the "easy comparison". Class intervals were created with the natural breaks "jenks" algorithm to maximise the difference between classes but this doesn't necessarily help to highlight change between budgets.
