### ISSUE TITLE
Constructed Wetlands - units

### ISSUE THREAD

**Issue by mz8i** [npalomin/shi_dataset_cdmx#3]
The CW data for colonias is supposed to be displayed as % / sqm, and the data on alcaldias level as the total budget (defined as calculated from the sqm value). Is there any specific reason for this? Is it because the alcaldias data doesn't necessarily cover every single colonia inside its borders, so showing a percentage or total square metres doesn't make sense?

**Comment by npalomin** [comment]
The data for CW Colonias is displayed as sqm (total for Colonia). Variable name "CW_sqm"

And the data for Alcaldia is in pesos which can be calculated from the sqm value.

Table below from section "Indices classes (or levels) & colour schemes"

| Budget         | Formula         |
|----------------|-----------------|
| Budget (pesos) | CW_sqm \* 18000 |

**Comment by mz8i** [comment]
So just to confirm - the CW percentage value should never be mapped, and is only used for the population impacted calculation?

**Comment by npalomin** [comment]
Yes. `CW_perc` is used to calculate "Population impacted" in the summary panel (see [formulas](https://github.com/npalomin/shi_dataset_cdmx#benefits-variables))
