### ISSUE TITLE
Colonias with missing name

### ISSUE THREAD

**Issue by mz8i** [npalomin/shi_dataset_cdmx#4]
There's a total of 30 rows in the colonias dataset where the colonia doesn't have a name (`"Colonia": null`) - should we just figure out a way to display the data gracefully, or would it be possible to manually correct the data? Unless these colonias actually do not have a name...

**Comment by npalomin** [comment]
I don't think we're in a position to complete the data. The missing values are inherited from the 'official' and original source. We could either leave the field empty or it could have the `"ID_Colonia"` value for those specific cases.

**Comment by mz8i** [comment]
That makes sense. I need to display something fairly readable in the
interactive list of all regions, so will maybe try "Colonia <ID>"
