### ISSUE TITLE
Weighting values

### ISSUE THREAD

**Issue by mz8i** [npalomin/shi_dataset_cdmx#5]
Could we add information to the repository about the weightings for each scenario?
The SVG icons have been added but I actually created a mechanism to display the circular gauges with the weightings inside the app in a more interactive way, but I'd need to have the 8 weighting values (0.0 - 1.0) for each of the three scenarios.

**Comment by npalomin** [comment]
The Weightings [section](https://github.com/npalomin/shi_dataset_cdmx/blob/main/README.md#weightings) was added. I will add the explanatory text for all Indices in this section too.
