### ISSUE TITLE
Base maps

### ISSUE THREAD

**Issue by mz8i** [npalomin/shi_dataset_cdmx#6]
The current prototype uses a CARTO Positron style base map, as it was the closest to the mockups I could quickly find. But it's not completely grey map. Let me know if there's another URL for a tileset I should use. Would have to be raster currently as we're not using Mapbox.

**Comment by npalomin** [comment]
This one is the version I used for the [interactive mock-ups](https://npalomin.github.io/BGS/2bu_2ye.html). 

It is a [Mapbox style](https://api.mapbox.com/styles/v1/npalomin/ckkfbcl5622tv17rzxz1lpt33.html?fresh=true&title=view&access_token=pk.eyJ1IjoibnBhbG9taW4iLCJhIjoiY2owMDF5YXQxMDA2eDMybmwwd2tqYTU3bSJ9.Icvrku6Q57o8L0gncJI89g) based on satellite imagery `https://api.mapbox.com/styles/v1/npalomin/ckkfbcl5622tv17rzxz1lpt33/tiles/256/{z}/{x}/{y}@2x?access_token=pk.eyJ1IjoibnBhbG9taW4iLCJhIjoiY2owMDF5YXQxMDA2eDMybmwwd2tqYTU3bSJ9.Icvrku6Q57o8L0gncJI89g`. 

@arretchecamila might be able to provide details of the base map in the PDF mock-ups.

**Comment by arretchecamila** [comment]
In the mockup we used the contour of a DEM file. We have it as shapefile but it may be too heavy, right?

**Comment by npalomin** [comment]
The DEM basemap could be processed as tiles in Mapbox, but I'm not certain how long it will take. @arretchecamila what are your thoughts on this [Mapbox style](https://api.mapbox.com/styles/v1/npalomin/ckkfbcl5622tv17rzxz1lpt33.html?fresh=true&title=view&access_token=pk.eyJ1IjoibnBhbG9taW4iLCJhIjoiY2owMDF5YXQxMDA2eDMybmwwd2tqYTU3bSJ9.Icvrku6Q57o8L0gncJI89g#13.37/-33.43981/-70.64911)?
